[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ipcl-python"
authors = [{name = "Sejun Kim", email = "sejun.kim@intel.com"}]
dynamic = ["version", "description"]
